
NO_GPU: 0                 # 1: ignore IDs above and run on CPU, 0: run on GPUs with IDs above
NUM_ENVIRONMENTS: 1      # number of environments (per agent process)
DUMP_LOCATION: datadump   # path to dump models and log
EXP_NAME: debug       # experiment name
VISUALIZE: 0              # 1: render observation and predicted semantic map, 0: no visualization
PRINT_IMAGES: 1           # 1: save visualization as images, 0: no image saving
GROUND_TRUTH_SEMANTICS: 0 # 1: use ground-truth semantics (for debugging / ablations)
seed: 1


### TODO: Environment Config
ENVIRONMENT:
  max_num_sub_task_episodes: 5
  turn_angle: 10.0        # agent turn angle (in degrees)


AGENT:
  max_steps: 500          # maximum number of steps before stopping an episode
  panorama_start: 0       # 1: turn around 360 degrees when starting an episode, 0: don't
  exploration_strategy: seen_frontier  # exploration strategy ("seen_frontier", "been_close_to_frontier")
  radius: 0.05            # robot radius (in meters)
  store_all_categories: True  # whether to store all semantic categories in the map or just task-relevant ones

  SEMANTIC_MAP:
    semantic_categories: langnav_cat # map semantic channel categories ("coco_indoor", "longtail_indoor", "mukul_indoor")
    num_sem_categories: 16           # number of map semantic channel categories (16, 257, 35)
    global_downscaling: 2    # ratio of global over local map
    du_scale: 1              # frame downscaling before projecting to point cloud

    # erosion and filtering to reduce the number of spurious artifacts
    dilate_obstacles: False
    dilate_size: 3
    dilate_iter: 1
    exploration_type: 'default'
    max_depth: 5.0 # hacky (for goat agent module)

    goal_filtering: True

    record_instance_ids: True  # whether to predict and store instance ids in the map

  PLANNER:
    collision_threshold: 0.20       # forward move distance under which we consider there's a collision (in meters)
    min_obs_dilation_selem_radius: 2    # radius (in cells) of obstacle dilation structuring element
    obs_dilation_selem_radius: 2    # radius (in cells) of obstacle dilation structuring element
    goal_dilation_selem_radius: 10  # radius (in cells) of goal dilation structuring element
    use_dilation_for_stg: False      # use dilated goals for estimating short-term goals - or just reaching
    map_downsample_factor: 1            # optional downsampling of traversible and goal map before fmm distance call (1 for no downsampling, 2 for halving resolution)
    map_update_frequency: 1             # compute fmm distance map every n steps 
    step_size: 5                    # maximum distance of the short-term goal selected by the planner
    discrete_actions: True         # discrete motion planner output space or not
    planner_type: "old"             # ("old", "new") where "new" is the latest one being used for spot in real world

  SUPERGLUE:
    max_keypoints: 1024
    keypoint_threshold: 0.005
    nms_radius: 4
    superglue_model: indoor           # or outdoor
    sinkhorn_iterations: 20
    match_threshold: 0.2
    score_function: confidence_sum    # or match_count
    score_thresh_image: 24.5  # real-world experiments used 6.0
    score_thresh_lang: 0.24
    match_projection_threshold: 0.2   # confidence must be at least this high to project as goal point.
    goto_past_pose: False
    batching: False

### 
LANGUAGE_TASKS:
  tasks1:
    category: couch
    description: Go to the couch in the living room.
    type: languagenav # TODO: from preprocess_goal
    semantic_id: 1 # TODO: from preprocess_goal
  task2:
    category: refrigerator
    description: Go to the refrigerator.
    type: languagenav # TODO: from preprocess_goal
    semantic_id: 9 # TODO: from preprocess_goal
  tasks3:
    category: cup
    description: Find a cup of coffee.
    type: languagenav # TODO: from preprocess_goal
    semantic_id: 13 # TODO: from preprocess_goal
